#Fundamentals

In [3]:
import torch
import pandas as pd
import matplotlib as plt
print(torch.__version__)  #see the pytorch version

2.8.0+cpu


## Intro to tensors
We can create tensors by using this command: torch.tensor(value)
Tensors are usedto store data;We can only put in numbers. Numbers are not allowed

In [5]:
# scalar:just one value
scalar = torch.tensor(2)

print(scalar,f'The dimension of scalar is {scalar.ndim}' )

tensor(2) The dimension of scalar is 0


In [6]:
#Vector:it is a set of value, like a one dimension array
vector = torch.tensor([3,3,4])
print(f'the vector {vector} has a dimension of {vector.ndim} and its size is {vector.shape}' )

the vector tensor([3, 3, 4]) has a dimension of 0 and its size is torch.Size([3])


In [10]:
#Matrix:it is 2dim array: it is like a squarre
matrix = torch.tensor([
    [3,4,4  ,9],
    [6,8,989,6760]
])
print(f'the matrix {matrix} has a dimension of {matrix.ndim} and its size is {matrix.shape}' )
print(f'The first row of the matrix : { matrix[0] } ,the second column is {matrix[1]}')
print(matrix[0][1])

the matrix tensor([[   3,    4,    4,    9],
        [   6,    8,  989, 6760]]) has a dimension of 2 and its size is torch.Size([2, 4])
The first row of the matrix : tensor([3, 4, 4, 9]) ,the first column is tensor([   6,    8,  989, 6760])


In [17]:
#Higher dimensinon tensors
#Tensor are not limited to 2Dimension.We can go higher 4 5 999
#3D is like a cube
#4d is set of cube
#here we just craft a 4dimension
#Always kep in mind this kind of presentation ...With exerciceyou will learn and master how it worked
tensor = torch.tensor([
    [
        [
            [1,7,82,23,534,6436],[23,989,826,64,57,57]
        ],
        [
            [563,28,743,645,645,7],[45,745,745,7,45,542]
        ]
    ],
    [
        [
            [1,7,84,564,57,8],[23,989,8,268,78,9]
        ],
        [
            [563,28,743,645,645,7],[45,745,745,7,45,542],
        ],
    ]
])
print(f'the matrix {tensor} has a dimension of {tensor.ndim} and its size is {tensor.shape}' )
print(matrix[0][1])

##try yourself for a better and deeper understanding

the matrix tensor([[[[   1,    7,   82,   23,  534, 6436],
          [  23,  989,  826,   64,   57,   57]],

         [[ 563,   28,  743,  645,  645,    7],
          [  45,  745,  745,    7,   45,  542]]],


        [[[   1,    7,   84,  564,   57,    8],
          [  23,  989,    8,  268,   78,    9]],

         [[ 563,   28,  743,  645,  645,    7],
          [  45,  745,  745,    7,   45,  542]]]]) has a dimension of 4 and its size is torch.Size([2, 2, 2, 6])
tensor(4)


## Random tensors
# We usually initialize tensors with some random data. With suitable algorithms such gradient descent, their values are optimized


In [20]:
#For setting random tensor,this is he syntax : torch(dimension)
random2DTendor = torch.rand(3,2)
random3DTendor = torch.rand(3,2,2)
print(random2DTendor)
print(random3DTendor)

tensor([[0.5131, 0.0236],
        [0.3865, 0.6027],
        [0.0373, 0.1401]])
tensor([[[0.7136, 0.4570],
         [0.4479, 0.5501]],

        [[0.0599, 0.3854],
         [0.2199, 0.2316]],

        [[0.7420, 0.1915],
         [0.7636, 0.9548]]])


In [23]:
# Make a tensor which has the same dimension than an picture or image: height weight color channel (R,G,B) 
random_image = torch.rand(size=(224,224,3))
#print(random_image)

## Zeros and Ones
Like in numpy, we can create a tensor fulled with zeros or ones

In [28]:
#the syntax is torch.zeros(dimension)
zeros_tensors = torch.zeros(size=(3,3,2))
ones_tensors = torch.ones(size=(3,2,2))
#print(zeros_tensors)
#print(ones_tensors)
print(f"The random tensor datatype is {ones_tensors.dtype}")

The random tensor datatype is torch.float32


In [30]:
# like in numpy we have arange method, like counting from one value to other with stepper
# syntax: torch.arange(start,end,step)
one_to_20 = torch.arange(1,20,3)
print(one_to_20)

tensor([ 1,  4,  7, 10, 13, 16, 19])


## Tensor datatype

In [31]:
#By default tensor have a datatype of float 32  tensor
float_32_tensor = torch.tensor([3.4,2.9,24.4],
                              dtype=None)

print(float_32_tensor)

tensor([ 3.4000,  2.9000, 24.4000])


## Tensor operations
We can handle tensors by using MATHS
* Addition and Substraction
* Multiplication and Division

In [33]:
# We can sum or subtract 2 tensors when they have the same dimension
tensor1 = torch.tensor([2,34,3,4,5])
tensor2 = torch.tensor([223,54,36,57,65])
print(tensor1-tensor2)
print(tensor1 + tensor2)
print(tensor1 + 4) # through BROADCASTING

tensor([-221,  -20,  -33,  -53,  -60])
tensor([225,  88,  39,  61,  70])
tensor([ 6, 38,  7,  8,  9])


In [37]:
# tensor Multiplication follows the algebre principle. 
tensor3 = torch.tensor([
            [1,2323,23,53,4],
            [23,989,826,64,57],
            [563,28,743,645,645],
            [45,745,745,7,45] 
])
tensor4 = torch.tensor([
            [1,7,84,564,57],
            [23,989,8,268,78],
            [563,28,743,645,64],
            [45,745,745,7,45]
])
print(tensor4 * 10)
print(tensor3 * tensor4) # Algebrist , remark torch transposes for multiplying

tensor([[  10,   70,  840, 5640,  570],
        [ 230, 9890,   80, 2680,  780],
        [5630,  280, 7430, 6450,  640],
        [ 450, 7450, 7450,   70,  450]])
tensor([[     1,  16261,   1932,  29892,    228],
        [   529, 978121,   6608,  17152,   4446],
        [316969,    784, 552049, 416025,  41280],
        [  2025, 555025, 555025,     49,   2025]])


In [38]:
# prebuilt function
print(torch.add(tensor1,tensor3))
print(torch.mul(tensor3,tensor4))


tensor([[   3, 2357,   26,   57,    9],
        [  25, 1023,  829,   68,   62],
        [ 565,   62,  746,  649,  650],
        [  47,  779,  748,   11,   50]])
tensor([[     1,  16261,   1932,  29892,    228],
        [   529, 978121,   6608,  17152,   4446],
        [316969,    784, 552049, 416025,  41280],
        [  2025, 555025, 555025,     49,   2025]])


## Tensor Aggregation
we just use some statistic methods such as min max

In [46]:
y = torch. arange(1,22)
# Finding the min
print(torch.min(y),y.min())

# Finding the max
print(torch.max(y),y.max())

# Finding the min
print(torch.min(y),y.min())

# Finding the min : take a caution. Mean works with particular datatype (float 32) if yo use Long datatype such float64 it will throw a error.Avoid long or float64
print(torch.mean(y.type(torch.float32)),y.type(torch.float32).mean())

#we can sum element of a tensor
print(y.sum())

tensor(1) tensor(1)
tensor(21) tensor(21)
tensor(1) tensor(1)
tensor(11.) tensor(11.)
tensor(231)


In [48]:
#When we work with probability and wanna find the highest, we often use the position of the highest
print(f'the argument_of_smallest :{ y.argmin()}')
print(f'the argument_of_highest :{ y.argmax()}')

the argument_of_smallest :0
the argument_of_highest :20
